version: '3.9'

volumes:
  mysql:
    driver: local

services:
  database:
    container_name: database
    build:
      context: ./docker/database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecom
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql:delegated
    command:
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--default-authentication-plugin=mysql_native_password'
  api-php:
    container_name: api-php
    build:
      context: ./docker/php
    volumes:
      - ./src:/var/www/ecom:cached
    depends_on:
      - database
  api-nginx:
    container_name: api-nginx
    build:
      context: ./docker/nginx
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/ecom:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-php
      - database
